name: "Build WebSocket server and restart it"
on:
  push:
    branches:
      - main

env:
  TOKENIZER_PATH: /home/quentin/EpiLinter-tokenizer

jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          ls
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Push the source code to the server
        run: scp -r ./* ${{ secrets.STAGING_SSH_USER }}@${{ secrets.STAGING_SSH_HOST }}:${{ env.TOKENIZER_PATH }}

      - name: Restart the server
        run: ssh staging 'cd ${{ env.TOKENIZER_PATH }} && docker-compose down --remove && docker-compose up -d --build'
