name: "Build WebSocket server and restart it"
on:
  push:
    branches:
      - main
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          ls
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Pull & build the source
        run: ssh staging 'cd /home/ubuntu/EpiLinter-tokenizer && git pull && make'

      - name: Restart the server
        run: ssh staging 'sudo systemctl restart epi-tokenizer'

  publish:
    name: "Build and publish new Docker Image"
    runs-on: ubuntu-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: "Login to DockerHub"
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u qudes --password-stdin

      - name: "Build image"
        run: |
          docker build -t qudes/epitokenizer:latest .
          docker push qudes/epitokenizer:latest


